const express=require("express")
const bookaddFunction = require("../controller/bookcontroller/addbookcontroller")
const deleltebook = require("../controller/bookcontroller/deletebookcontrole")
const getbook = require("../controller/bookcontroller/getbookcontroller")
const updatebook = require("../controller/bookcontroller/updatebookcontrole")
const Signup = require("../controller/signupController")
const Login = require("../controller/userLogin")
const protect = require("../middilware/tocken")
const getbookbyid = require("../controller/bookcontroller/getbookidcontroller")
const addclient = require("../controller/clientcontroller/addclient")
const getclient = require("../controller/clientcontroller/getclient")
const clientgetbyid = require("../controller/clientcontroller/getclientbyid")
const updateclient = require("../controller/clientcontroller/updateclient")
const deleteclient = require("../controller/clientcontroller/deleteclient")
const addcustomer = require("../controller/Customercontroller/addcustomer")
const getcustomer = require("../controller/Customercontroller/getcustomer")
const getcustomerbyid = require("../controller/Customercontroller/getcustomerbyid")
const updatecustomer = require("../controller/Customercontroller/updatecustomer")
const deletcustomer = require("../controller/Customercontroller/deletecustomer")
const addteammember = require("../controller/teammembercontroller/addteammember")
const getteam = require("../controller/teammembercontroller/getteammember")
const getteambyid = require("../controller/teammembercontroller/getteammemberbyid")
const updateteam = require("../controller/teammembercontroller/updateteammember")
const deleteteam = require("../controller/teammembercontroller/deleteteammember")
const addorder = require("../controller/ordercontroller/addorder")
const getorder = require("../controller/ordercontroller/getorder")
const getorderid = require("../controller/ordercontroller/getorderid")
const updateorder = require("../controller/ordercontroller/updateorder")
const deletorder = require("../controller/ordercontroller/deleteorder")




const router=express.Router()
const middilware=[protect]
router.route("/Signup").post(Signup)
router.route("/Login").post(Login)
router.route("/Jwt").post(middilware,Login)
router.route("/book").post(bookaddFunction)
router.route("/getbook").get(getbook)
router.route("/update/:id").put(updatebook)
router.route("/delete/:id").delete(deleltebook)
router.route('/getbyid/:id').get(getbookbyid)
router.route("/Client").post(addclient)
router.route("/getclient").get(getclient)
router.route("/getclient/:id").get(clientgetbyid)
router.route("/updateclient/:id").put(updateclient)
router.route("/deleteclient/:id").delete(deleteclient)
router.route("/Customer").post(addcustomer)
router.route("/getcustomer").get(getcustomer)
router.route("/getcustomer/:id").get(getcustomerbyid)
router.route("/updatecustomer/:id").put(updatecustomer)
router.route("/deletecustomer/:id").delete(deletcustomer)
router.route("/Teammember").post(addteammember)
router.route("/getteam").get(getteam)
router.route("/getteam/:id").get(getteambyid)
router.route("/updateteam/:id").put(updateteam)
router.route("/deletteam/:id").delete(deleteteam)
router.route("/Order").post(addorder)
router.route("/getorder").get(getorder)
router.route("/getorder/:id").get(getorderid)
router.route("/updateorder/:id").put(updateorder)
router.route("/deletorder/:id").delete(deletorder)


module.exports=router